server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    root: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ll123456
    hikari:
      maximum-pool-size: 1
      pool-name: selfHikariCP
      max-lifetime: 30000
      connection-timeout: 1000
      connection-test-query: SELECT 1